/**
 * Middleware for multi-language support
 * Auto-generated by Ailydian SEO Dashboard
 */

import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

const SUPPORTED_LOCALES = ["tr","en","de","fr","es","ru","ar","zh","it","pt"];
const DEFAULT_LOCALE = 'tr';

export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Check if pathname already has a locale
  const pathnameHasLocale = SUPPORTED_LOCALES.some(
    (locale) => pathname.startsWith(`/${locale}/`) || pathname === `/${locale}`
  );

  if (pathnameHasLocale) return;

  // Detect user's preferred language
  const acceptLanguage = request.headers.get('accept-language');
  const preferredLocale = acceptLanguage
    ?.split(',')[0]
    ?.split('-')[0];

  const locale = SUPPORTED_LOCALES.includes(preferredLocale || '')
    ? preferredLocale
    : DEFAULT_LOCALE;

  // Redirect to localized URL
  request.nextUrl.pathname = `/${locale}${pathname}`;
  return NextResponse.redirect(request.nextUrl);
}

export const config = {
  matcher: [
    // Skip all internal paths (_next, api, etc)
    '/((?!api|_next/static|_next/image|favicon.ico|robots.txt|sitemap.xml).*)',
  ],
};
